name: Kiosk Button - Release

trigger:
  branches:
    include:
    - master

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/KioskButton.sln'
  major: 4
  minor: 0
  patch: $(Build.BuildID)
  packProject: 'WorkerService/bin/Release/netcoreapp3.1/win10-x86'

steps:
- task: DotNetCoreCLI@2
  displayName: 'NuGet Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: 'NuGet.config'
    projects: '$(solution)'
    verbosityRestore: 'Quiet'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(solution)
    majorVersion: $(major)
    minorVersion: $(minor)
    patchVersion: $(patch)
    configuration: 'release'
    arguments: '--runtime win10-x86 --configuration release'

- task: OctopusPack@4
  inputs:
    PackageId: 'KioskAnnunciatorButton.WorkerService'
    PackageFormat: 'NuPkg'
    PackageVersion: '$(major).$(minor).$(patch)'
    SourcePath: '$(Build.SourcesDirectory)\$(packProject)'
    OutputPath: '$(Build.ArtifactStagingDirectory)'
    NuGetAuthor: 'Ryan Blackman'
    NuGetTitle: 'Kiosk Annunciator Button'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'OctopusPkg'
    publishLocation: 'Container'



- task: OctopusPush@4
  inputs:
    OctoConnectedServiceName: 'Octopus Deploy Service'
    Space: 'Spaces-1'
    Package: '$(Build.ArtifactStagingDirectory)/*'
    Replace: 'true'

- task: OctopusCreateRelease@4
  inputs:
    OctoConnectedServiceName: 'Octopus Deploy Service'
    Space: 'Spaces-1'
    ProjectGroup: 'ProjectGroups-21'
    ProjectName: 'Projects-203'
    Channel: 'Channels-203'
    DeployToEnvironment: 'Environments-1'
    DeployForTenants: '*'
    DeploymentProgress: true

- task: OctopusPromote@4
  inputs:
    OctoConnectedServiceName: 'Octopus Deploy Service'
    Space: 'Spaces-1'
    ProjectGroup: 'ProjectGroups-21'
    Project: 'Projects-203'
    From: 'Environments-1'
    To: 'Environments-21'
    ShowProgress: true
    DeployForTenants: '*'
