name: Kiosk Button - Release

trigger:
  branches:
    include:
    - master

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/KioskButton.sln'
  rt: 'win10-x86'
  buildConfiguration: 'Release'
  #major: '4'
  #minor: '0'
  #patch: $[counter('versioncounter', 0)]

steps:
- task: DotNetCoreCLI@2
  displayName: NuGet Restore
  inputs:
    command: restore
    feedsToUse: config
    nugetConfigPath: 'NuGet.config'
    projects: $(solution)
    verbosityRestore: 'quiet'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: $(solution)
    verbosityBuild: 'normal'
    arguments: '-runtime $(rt) --configuration $(BuildConfiguration)'


- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**\octopacked\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: 'Push to Octopus'
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg;!$(Build.ArtifactStagingDirectory)/**/tempNuGet*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'Octopus Nuget Feed'
