name: Release Service

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [win-x64, win-x86]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore Service/Mtd.Kiosk.Annunciator.Service.csproj

      - name: Build and Publish
        run: |
          dotnet publish Service/Mtd.Kiosk.Annunciator.Service.csproj \
            --configuration Release \
            --runtime ${{ matrix.arch }} \
            --self-contained true \
            --output publish_output \
            --no-restore
          zip -r service-${{ matrix.arch == 'win-x64' && 'x64' || 'x86' }}-${{ github.event.release.tag_name }}.zip publish_output

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            service-${{ matrix.arch == 'win-x64' && 'x64' || 'x86' }}-${{ github.event.release.tag_name }}.zip
